name: dotsot
description: "using this package you can easily log the Strings in to console. It helps to debug the code and increase the readability of the code."
version: 0.0.2
homepage: https://github.com/aarifhusaincom/dotsot

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
