// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALeOJUkMkn-2M8Jus2EXbeVac2LqwzMcQ',
    appId: '1:936967428287:web:365feeba4f1d03b2294e0a',
    messagingSenderId: '936967428287',
    projectId: 'fire-22072025',
    authDomain: 'fire-22072025.firebaseapp.com',
    storageBucket: 'fire-22072025.firebasestorage.app',
    measurementId: 'G-Q3L29PBMNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8hY558qWUQ-GthT9nf0PQnpXnk6iXcNk',
    appId: '1:936967428287:android:508e277ce9d816c9294e0a',
    messagingSenderId: '936967428287',
    projectId: 'fire-22072025',
    storageBucket: 'fire-22072025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVivbG4PuJHXjtpwmEPMS_eJnlMPp_lU',
    appId: '1:936967428287:ios:a960f64083be9ff2294e0a',
    messagingSenderId: '936967428287',
    projectId: 'fire-22072025',
    storageBucket: 'fire-22072025.firebasestorage.app',
    iosBundleId: 'com.example02082025.example02082025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVivbG4PuJHXjtpwmEPMS_eJnlMPp_lU',
    appId: '1:936967428287:ios:a960f64083be9ff2294e0a',
    messagingSenderId: '936967428287',
    projectId: 'fire-22072025',
    storageBucket: 'fire-22072025.firebasestorage.app',
    iosBundleId: 'com.example02082025.example02082025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALeOJUkMkn-2M8Jus2EXbeVac2LqwzMcQ',
    appId: '1:936967428287:web:fe4e23f7f14b00f8294e0a',
    messagingSenderId: '936967428287',
    projectId: 'fire-22072025',
    authDomain: 'fire-22072025.firebaseapp.com',
    storageBucket: 'fire-22072025.firebasestorage.app',
    measurementId: 'G-C9SGLRMR7Q',
  );
}
